#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit
fi
pam_mod=pam_unix.so
if [ ! -e /etc/pam.d/typtop-auth ]; then
    echo "Ah snap! Cannot find /etc/pam.d/typtop-auth. "
    echo "Try re-installing or manually copy it from the build folder."
    echo "Really sorry for this mishap."
    exit 1;
fi


if [ -d "/etc/pam.d/" ]; then
    for f in /etc/pam.d/*.orig; do
        if [ -e "$f" ]; then
            echo "Already backed up PAM config files at /etc/pam.d/*.orig. Have you already installed?"
            exit
        fi
    done
    if [ -e "/etc/pam.d/*.orig" ]; then
        exit
    fi
    pushd /etc/pam.d > /dev/null
    for f in /etc/pam.d/*; do
        # Don't insert typtop-auth in typtop-auth
        if [[ "$f" == *"typtop-auth"* ]]; then continue; fi
        # Don't insert typtop-auth if it is already there.
        grep typtop-auth $f; if [ "$?" == "0" ]; then continue; fi
        if [[ $(grep -e "^auth.*${pam_mod}" $f) ]]; then
            sed -i.orig "/^auth*.*${pam_mod}.*/iauth\tinclude\t\ttyptop-auth" $f
        fi
    done

    popd > /dev/null
    echo "Configuring PAM to use typtop with /etc/pam.d/ files"
elif [ -e "/etc/pam.conf" ]; then
    sed -i.orig "/^auth*.*${pam_mod}.*/iauth\tinclude\t\ttyptop-auth" /etc/pam.conf
    echo "Configuring /etc/pam.conf to use typtop"
else
    echo "Could not determine where to install pam config files, please do so manually"
fi


# Usage Agreement
# read -p "Do you want to send anonymous usage data for our research?" -n 1 -r
# echo    # (optional) move to a new line
# if [[ $REPLY =~ ^[Yy]$ ]]; then
#   echo "Thanks!!"
# fi

cat @CPACK_PACKAGING_INSTALL_PREFIX@/@INSTALL_DATA_DIR@/typtop.d/welcome.txt