#!/usr/bin/env bash

# TO delete old typtop installations

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit
fi

if [ -d "/etc/pam.d/" ]; then
    for f in /etc/pam.d/*.orig; do
        if [ -e "$f" ]; then
            mv "$f" "${f%.*}"
        fi
    done
    rm -f /etc/pam.d/typtop-auth
    echo "Reverting to original files"
elif [ -e "/etc/pam.conf" ]; then
    mv /etc/pam.conf.orig /etc/pam.conf
    echo "Reverting to original files"
else
    echo "Could not determine where to install pam config files, please do so manually"
fi

# try calling typtop --uninstall
typtopexec=$(which typtops.py) || /usr/local/bin/typtops.py
if [ "$typtopexec" ]; then
   ${typtopexec} --uninstall
fi

pip show typtop
if [[ "$?" == "0" ]]; then
   pip -q uninstall --yes typtop word2keypress zxcvbn zxcvbn-python >&/dev/null
fi

if [ -f /usr/local/bin/typtop-uninstall.sh ]; then
   bash /usr/local/bin/typtop-uninstall.sh
else
   rm -rf /usr/local/bin/typtop*
fi

rm -rf /var/log/*typtop*log /usr/local/bin/*typtop* /usr/loca/etc/security/*typtop*
