#!/usr/bin/env bash
db_root=/usr/local/etc/typtop.d
rm -rf ${db_root}

if [ -d "/etc/pam.d/" ]; then
    pushd /etc/pam.d/ >/dev/null
    for f in *.orig; do
        if [ -e $f ]; then
            # echo "mv $f ${f%.*}"
            mv $f ${f%.*}
        fi
    done
    popd > /dev/null

    # sed -i.bak 's/auth\tsubstack\ttyptop-auth/auth\trequired\tpam_unix.so/g'
    rm -f /etc/pam.d/typtop-auth
    echo "Reverting to original files"
elif [ -e "/etc/pam.conf" ]; then
    mv /etc/pam.conf.orig /etc/pam.conf
    echo "Reverting to original files"
else
    echo "Could not determine where to install pam config files, please do so manually"
fi
